# Site
repository: o-tao/o-tao.github.io
favicon: images/icon.ico

# Content configuration version
version: 2

# Personal info
name: 오상민
title: Backend Developer
email: osmin9027@gmail.com
phone: 010-5472-9027
website: https://tao-tech.tistory.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  o-tao
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-blog
#  url: https://tao-tech.tistory.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: 자기소개
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  **저는 웹 서버 개발의 전체 사이클을 스스로 학습하고 구현한 경험이 있습니다.** <br>
  <p> ERD 설계 및 API 구현부터 AWS EC2, RDS(MySQL), ElastiCache(Redis)를 활용한 인프라 구축, GitHub Actions CI/CD, AWS S3, CodeDeploy를 활용한 자동화 배포 까지 전 과정을 직접 구성하였습니다. </p>
  <br>
  **저는 문제를 성장의 기회로 삼아 더 나은 결과를 만들어내는 데에 몰입합니다.** <br>
  <p> 기술적 한계나 문제에 직면했을 때 그것을 기회삼아 학습하여 해결 방안을 찾고, 팀원과 공유하여 다수의 피드백을 얻어 함께 기술적 문제를 해결하고 성장하는 것에 큰 성취감을 얻습니다. 문제 해결 시간 단축을 위해 작업을 작은 단위의 Task로 분리하고, 코드 리뷰를 통해 협업을 고려한 코드 작성과 유지보수성을 높이는 방식을 고민했습니다. <br>
  이 과정에서 테스트 코드를 작성하며 코드의 신뢰성을 높이는 습관을 자연스럽게 익혔고, 스스로 학습한 지식을 정리하여 팀원에게 공유해 더 나은 결과를 만들어내는 데에 몰입하며 성장해왔습니다. </p>
  <br>
  **마지막으로, 저는 경험을 공유하여 함께 성장하는 것에 큰 가치를 느낍니다.** <br>
  <p> 누군가에게 설명할 수 있을 때 비로소 저의 지식이 되고, 그것이 곧 저의 성장이 된다고 생각합니다.<br>
  학습한 내용과 경험을 공유하고 피드백을 얻는 것에 큰 보람을 느껴 꾸준히 블로그에 기록하고 있습니다.<br>
  지속적인 학습과 개선을 통해 좋은 영향을 주어 함께 성장하는 개발자가 되고자 합니다. </p>

content:
  - title: 기술 스택 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Java, SpringBoot
          - SpringDataJPA, MyBatis, QueryDSL
          - JUnit5
      - layout: left
        title: DevOps
        description: |
          - MySQL, MariaDB
          - AWS (EC2, RDS, ElastiCache, S3, CodeDeploy, SES)
          - Docker Compose
      - layout: left
        title: Tools
        description: |
          - IntelliJ, Jira, Slack, Git

  - title: 경력 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BU Technology
        sub_title: 기술교범팀 Fullstack
        caption: 2025.03 ~ 현재 재직중
        description: | # this will include new lines to allow paragraphs
          **기존 서비스 유지보수 및 SpringMVC 기반 레거시 시스템을 SpringBoot 기반으로의 이관에 참여**
          - **공통 모듈 개발**
            - 콘텐츠 유형별 링크 이동, 이미지 표출 방식, 자료 유형별 메인 페이지 렌더링을 위한 서버 사이드 공통 비즈니스로직을 모듈화하여 서비스 전반의 데이터 처리 및 API 응답 일관성 확보
            - 프론트엔드 화면 구성과 연계되는 공통 처리 로직의 재사용성을 높이기 위해 객체 및 컴포넌트 기반 구조로 설계
            - 중복 코드 제거를 통해 전체 개발 효율성과 유지보수성 향상
          
          - **관리자 시스템 기능 개발**
          
            📈 사용자 접속 로그 수집, 처리 및 통계 기능 개발
              - 사용자 접속 로그 수집, 저장, 처리 기능 구현, 이를 위한 REST API 제공
              - 프론트엔드 관리자 페이지에서 통계 데이터를 시각화하기 위해 ECharts를 활용한 시각화 컴포넌트를 개발 및 연동
              - 전체, 연도별, 월별, 일별 접속자 수, 책자별 조회 통계 등 지표를 시각화하여 운영 인사이트 제공
          
            🧭 사용자 행동 로그 수집, 처리 기능 개발
              - 사용자 콘텐츠 이용 및 행동 로그 수집, 저장, 처리를 위한 REST API 개발
              - 로그 코드, 명칭, 설명, 등록일 기준의 로그 테이블 시각화 처리
              - 날짜 기준 검색 및 offset 기반 페이지네이션 처리 구현을 통해 로그 탐색 편의성 강화
          
            📝 용어 편집 기능 개발
              - 관리자가 용어 정보를 등록, 수정, 삭제할 수 있는 CRUD 기능 구현
          
            🌐 다국어(i18n) 처리
            - Spring Message Properties 기반의 다국어 처리 및 동적 언어 전환 기능 구현
          
            📂 콘텐츠 변경 이력 기능 개발
              - 콘텐츠 변경 이력을 트리 구조로 시각화하여 운영 인사이트 제공
              - 변경 버전별 상세 정보 확인 기능 구현
            
          - **기술 스택**
            - **Backend**: Java, SpringBoot, MyBatis, SpringSecurity
            - **Database**: Oracle, MySQL, MariaDB
            - **Tools**: Git
          
          ---
          
          **업무 자동화 개발 참여**
          - **멀티 모듈 아키텍처 구성**
            - admin, worker, domain으로 구성된 멀티모듈 구조 설계
            - domain: JPA Entity 중심의 라이브러리 모듈
            - admin: 개발자용 API 및 서버 상태 관리
            - worker: 크롤링 및 AI 기반 업무 자동화 수행
          
          - **admin 모듈 기능 개발**
            - 서버 상태 체크 기능 구현
              - Scheduler 실행주기: fixedRate = 600000 (작업 시작 기준 10분)
              - 정상 응답 시 heartbeatAt 필드 갱신
            - 일감 생성 기능 설계 및 구현
              - 유저별 실행 정책을 통해 동적 일감 생성
              - 업무 시간(ex: 09:00 ~ 18:00)에만 일감이 생성되도록 구현
              - 분단위 지정 시간(ex: 30분 - 60분) 내 무작위 시점에 생성
          
          - **worker 모듈 기능 개발**
            - 크롤링 기능 설계 및 구현
              - admin 모듈에서 생성한 PENDING 상태의 일감에 대해 크롤링 작업 수행
              - Scheduler 실행 주기: fixedDelay = 1000 (이전 작업이 끝난 후 1초)
              - Selenium을 통해 게시글 제목, 본문, 작성 시간 수집
              - 수집 데이터는 AiApprovalTask 테이블에 PENDING 상태로 저장
            - AI 필터링 기능 구현
              - Scheduler 실행 주기: fixedDelay = 1000 (이전 작업이 끝난 후 1초)
              - 크롤링 작업에서 생상한 PENDING 상태의 AiApprovalTask에 대해 작업 수행
              - AI가 사용자의 지침에 따라 AI_APPROVAL / AI_REJECTION 상태로 Reason과 함께 자동 분류
            - AI, Selenium 기반 업무 자동화 처리
              - Scheduler 실행 주기: fixedDelay = 1000 (이전 작업이 끝난 후 1초)
              - AiApprovalTask의 AI_APPROVAL 상태에 대해 게시글 자동 응답 생성, 생성된 일감 GENERATED 상태로 업데이트
              - GENERATED 상태의 업무를 사용자 직접 승인, 거부에 따른 업데이트
              - 유저가 승인한(USER_APPROVAL)업무에 대해 Selenium을 활용하여 유저 실행정책을 통한 코멘트 작성 자동화
          
          - **기술 스택**
            - **Backend**: Kotlin, SpringBoot, SpringDataJPA, QueryDSL, Selenium, OpenFeign, OpenAI
            - **Database**: MySQL
            - **DevOps**: AWS (EC2, RDS, CloudWatch), DockerCompose
            - **Tools**: Git
          
          ---
          
          **개발 생산성 기여**
            - Docker Compose를 통해 데이터베이스 기본 사용자 설정 및 초기 데이터 자동화 구성
              - 평균 개발 환경 세팅 시간 수일 → 약 10분으로 단축
            - 통합 테스트를 위한 일관된 테스트 환경 제공
              - Docker 기반 컨테이너화된 SpringBoot 앱 이미지 제공, 팀원들이 동일한 데이터 환경에서 테스트 가능하도록 지원
            - 사내 미니 프로젝트: OpenAI 기반 코드 리팩토링 제안 기능 구현
              - 특정 커밋에 대해 사내 코드 규칙 기반 Prompt 작성
              - OpenAI를 통해 코드 리뷰 및 리팩토링 방향을 Slack 메세지로 자동 제안

  - title: 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 구똑 - 구독을 똑똑하게
        sub_title: Backend
        caption: |
          <p>2024.12 ~ 2025.05</p>
          <a href="https://github.com/TeamGuttok/back" target="_blank"> <img src="https://img.shields.io/badge/gitHub%20Repository-Back-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="github"> </a>
        quote: >
          점차 다양해지는 구독 서비스와 고정 지출을 똑똑하게 관리하기 위한 플랫폼
        description: | # this will include new lines to allow paragraphs
          **주요 역할**
          
          **프로젝트 ERD 설계**
          - 데이터 모델링 및 관계 설계를 통한 데이터 구조 구축
          
          **공통 모듈 개발**
          - AWS Simple Email Service(SES)를 활용하여 서비스 전반에서 재사용 가능한 이메일 발송 모듈 구현 <a href="https://tao-tech.tistory.com/25" target="_blank"> <img src="https://t1.daumcdn.net/cfile/tistory/9935084A5B9541D014?style=flat-square&logo=Tistory&logoColor=white" width="15" alt="Tistory"> </a>
          
          **결제 일정 리마인드 기능 개발**
          - Spring Scheduler를 활용하여 구독 결제일 하루 전 사용자에게 자동으로 이메일 리마인드 발송 구현
          - 서비스 확장성을 고려하여 Scale-out 환경에서 Scheduler의 중복 실행을 방지하기 위해 Redis 분산락 기반의 Shedlock 적용 <a href="https://tao-tech.tistory.com/31" target="_blank"> <img src="https://t1.daumcdn.net/cfile/tistory/9935084A5B9541D014?style=flat-square&logo=Tistory&logoColor=white" width="15" alt="Tistory"> </a>
          
          **구독 서비스 관리 기능 개발**
          - 사용자 구독항목 CRUD 기능, 구독 서비스 리스트, 검색 기능 개발
          - 구독항목 생성 전 구독 서비스 선택란을 각각의 코드값으로 하여 리스트 응답 처리, QueryDSL의 동적 쿼리를 활용하여 Like 검색 기능 구현
          - 사용자 구독항목 리스트 QueryDSL의 동적 쿼리를 활용하여 no-offset 방식의 페이징 처리
          
          **알림 관리 기능 개발**
          - 회원가입, 결제 알림 등 애플리케이션 내 알림에 대한 CRUD 기능 개발
          - QueryDSL의 동적 쿼리를 활용해 no-offset 방식의 페이징 처리
          - 알림 읽음 처리 시 벌크 업데이트 적용
          - 알림 삭제 시 벌크 삭제 적용
          
          **기술 스택**
          - **Backend**: Java, SpringBoot, SpringDataJPA, QueryDSL, SpringSecurity, JUnit5
          - **Database**: MySQL, Redis, H2(테스트)
          - **DevOps**: AWS (EC2, RDS, ElastiCache, SES), Docker
          - **Tools**: Jira, Swagger, Git
               
          ---

      - layout: left
        title: TodoList
        sub_title: Backend
        caption: |
          <p>2024.08 ~ 2024.11</p>
          <a href="https://github.com/o-tao/todo-list" target="_blank"> <img src="https://img.shields.io/badge/gitHub%20Repository-Back-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="github"> </a>
        quote: >
          할 일(Todo) 관리 기능을 제공하는 REST API 기반 애플리케이션
        description: | # this will include new lines to allow paragraphs
          **REST API 개발**
          - Todo CRUD 기능 개발 (테스트 커버리지 80% 달성)
          - Spring Data JPA, QueryDSL을 사용하여 동적 쿼리를 이용한 검색 및 페이지네이션 구현 <a href="https://tao-tech.tistory.com/17" target="_blank"> <img src="https://t1.daumcdn.net/cfile/tistory/9935084A5B9541D014?style=flat-square&logo=Tistory&logoColor=white" width="15" alt="Tistory"> </a>
          - Redis를 Session Storage로 활용한 사용자 인증, 인가 구현 <a href="https://tao-tech.tistory.com/19" target="_blank"> <img src="https://t1.daumcdn.net/cfile/tistory/9935084A5B9541D014?style=flat-square&logo=Tistory&logoColor=white" width="15" alt="Tistory"> </a>
          - 외부 라이브러리 없이 CustomAnnotation을 사용하여 Interceptor, ArgumentResolver를 이용한 인증, 인가 직접 구현
          - docker-compose를 활용한 MySQL, Redis 기반 로컬 개발 환경 구성   
          
          **배포 인프라, CI/CD 파이프라인 구축** <br>
          **[AWS]**
          - EC2, RDS(MySQL), ElastiCache(Redis) 리소스 구성 <a href="https://tao-tech.tistory.com/20" target="_blank"> <img src="https://t1.daumcdn.net/cfile/tistory/9935084A5B9541D014?style=flat-square&logo=Tistory&logoColor=white" width="15" alt="Tistory"> </a>
          - 보안그룹 설정을 통해 인스턴스 간 연결 구성
          - S3와 CodeDeploy를 활용한 배포 자동화 환경 구축
          - IAM 설정을 통해 AWS 리소스에 대한 권한 제어 및 보안 설정
          
          **[CI/CD]**
          - CI/CD 파이프라인 구축 <a href="https://tao-tech.tistory.com/21" target="_blank"> <img src="https://t1.daumcdn.net/cfile/tistory/9935084A5B9541D014?style=flat-square&logo=Tistory&logoColor=white" width="15" alt="Tistory"> </a>
          - GitHub Actions를 활용하여 미리 구성된 Docker Compose 환경에서 테스트 코드 자동 실행 (CI)
          - GitHub Secrets 환경변수로 JAR 파일 빌드 후 S3에 업로드, AWS CodeDeploy로 EC2에 자동 배포 (CD)
          
          **기술 스택**
          - **Backend**: Java, SpringBoot, SpringDataJPA, QueryDSL, JUnit5
          - **Database**: MySQL, Redis, H2(테스트)
          - **DevOps**: AWS (EC2, RDS, ElastiCache, S3, CodeDeploy), Docker
          - **Tools**: Git
              
          ---

      - layout: left
        title: WarriorDining
        sub_title: Fullstack
        caption: |
          <p>2024.10 ~ 2024.11</p>
          <a href="https://github.com/warrior-dining/warrior-dining-back" target="_blank"> <img src="https://img.shields.io/badge/gitHub%20Repository-Back-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="github"> </a>
          <br>
          <a href="https://github.com/warrior-dining/warrior-dining-front" target="_blank"> <img src="https://img.shields.io/badge/gitHub%20Repository-Front-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="github"> </a>
        quote: >
          바쁜 현대인들을 위한 효율적인 음식점 예약 서비스
        description: | # this will include new lines to allow paragraphs
          **주요 역할** <br>
          **백엔드 기능 개발**
          - 회원가입, 비밀번호 찾기, 내정보 조회, 회원탈퇴 API 구현
          - ERD를 참조하여 JPA 설계
          - SpringSecurity, JWT 기반 인증, 인가 구현
          - GlobalExceptionHandler를 사용하여 전역 예외 처리 구현   
          
          **프론트엔드 기능 개발**
          - 회원가입, 로그인, 비밀번호 찾기, 내정보 조회, 회원탈퇴 페이지 및 기능 구현
          - 로그인 액세스 토큰, 리프레쉬 토큰 발급에 대한 Context 전역 처리
          - 회원 열람 페이지에서 axios 요청 시 토큰 검증을 전역 처리

          **기술 스택**
          - **Backend**: Java, SpringBoot, SpringDataJPA, SpringSecurity
          - **Frontend**: React.js(JavaScript)
          - **Database**: MariaDB
          - **DevOps**: Docker

  - title: 교육 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 하이미디어 아카데미
        caption: 2024.05 ~ 2024.10 수료
        description: | # this will include new lines to allow paragraphs
          - React.js와 Springboot 활용 자바(JAVA) 풀스택(프론트엔드&백엔드)개발자
          - JAVA 프로그래밍 언어 등 디지털 기술을 기반으로 다양한 기기의 융합, 콘텐츠의 융합을 통해 모바일 플랫폼에서 활용할 수 있는 웹&앱 콘텐츠의 기획, 구현, 설계, 제작, 운용 및 시험을 수행하는 업무를 수행

      - layout: left
        title: 학점은행제
        sub_title: 컴퓨터공학 전공
        caption: 2022.09 ~ 재학중

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
